### ISSUE TITLE
http://faucet.cryptokylin.io/get_token?account_name is broken 

### ISSUE THREAD

**Issue by venediktov** [cryptokylin/CryptoKylin-Testnet#21]
When I try to use this endpoint I always get 

> {"msg": "reach 24 hours max token amount"}

I had to go and ask admins on telegram , now I can't even do that as admins closed my access to telegram .

If this feature is not available please update your README.md 

https://github.com/cryptokylin/CryptoKylin-Testnet#get-free-tokens

**Comment by zsq978663747** [comment]
we have a limit, in the 24 hours, one ip only can recive 1000 tokens.

**Comment by zsq978663747** [comment]
what did you use to get token? browser or cmd?

**Comment by zsq978663747** [comment]
we have a limit, in the 24 hours, one ip only can recive 1000 tokens.what did you use to get token? browser or cmd?you can use cmd try it.

**Comment by zsq978663747** [comment]
you can use this url ```curl http://13.230.87.138:80/get_token?111111111ooo```

**Comment by jurosh** [comment]
I am getting `{"msg": "transaction failed, possible reason: account does not exist"}` now...

Tested with two different account accounts... eg. curl http://13.230.87.138:80/get_token?juroshjurosh

Account exist: https://kylin.eosq.app/account/juroshjurosh

**Comment by noprom** [comment]
The faucet api endpoint is stable now, so this issue should be closed now.

**Comment by ekkis** [comment]
I'm happy to hear the endpoint is stable but it's documented on the website as `curl http://faucet.cryptokylin.io/get_token?$ACCOUNT` for which I get a 404.  what is the correct endpoint? and could the website (https://docs.liquidapps.io/en/v1.4/developers/kylin-account.html) get updated please?

**Comment by ekkis** [comment]
> you can use this url `curl http://13.230.87.138:80/get_token?111111111ooo`

curl: (7) Failed to connect to 13.230.87.138 port 80: Operation timed out

is there a list of addresses one could use?

**Comment by ekkis** [comment]
ah.  for future reference, the correct url is `http://faucet.cryptokylin.io/get_token/$ACCOUNT`
