### ISSUE TITLE
ERROR: manifest for cryptokylin/eos:v1.4.4 not found

### ISSUE THREAD

**Issue by lixiaodong** [cryptokylin/CryptoKylin-Testnet#30]
Docker version 18.09.0, build 4d60db4

when i run : ./run.sh

this error shows.

**Comment by noprom** [comment]
This problem should be resolved now, beacuse I forget to upload the docker image to the docker hub: `cryptokylin/eos:v1.4.4`.

**Comment by lixiaodong** [comment]
thank you very much.

**Comment by noprom** [comment]
Should be closed now.
