### ISSUE TITLE
root@jetty:/opt/CryptoKylin-Testnet/fullnode# docker-compose -f docker-compose-kylin-init.yaml up -d fullnode_nodeosd_1 is up-to-date

### ISSUE THREAD

**Issue by lixiaodong** [cryptokylin/CryptoKylin-Testnet#32]
root@jetty:/opt/CryptoKylin-Testnet/fullnode# docker-compose -f docker-compose-kylin-init.yaml up -d
fullnode_nodeosd_1 is up-to-date

----------------------------------------------------------------------------------------------
this tips shows when i run "docker-compose -f docker-compose-kylin-init.yaml up -d"

so ,what can i do ?

**Comment by noprom** [comment]
Nothing else to do, the node is already syncing data from the peers in the network.

**Comment by lixiaodong** [comment]
thanks
