### ISSUE TITLE
sync with mongo_db_plugin too slow

### ISSUE THREAD

**Issue by hippokylejan** [cryptokylin/CryptoKylin-Testnet#6]
when using mongo_dp_plugin to filter historical data into mongodb, the blockchain sync speed become extremely slow. The time interval between nodeosd's "incoming block" log will be about 7 minutes. And during this interval, mongodb still have tasks to proceed. It seems that the mongo_db_plugin process speed or mongodb's operation speed is too slow. Besides, after a while, the mongodb process will restart automatically and the nodeosd process will exit by itself.

4 core CPU, 16G Memory, 1T SSD

**Comment by winlin** [comment]
@noprom do you have same issue?
@hippokylejan can you disable the mongo_db_plugin and check the sync speed?

**Comment by noprom** [comment]
@hippokylejan Which kind of `nodeos` version do you use?
As far as I know, syncing data to `mongodb` instance is a computation expensive operation, could you please try to scale up your machine which runs `nodeos`? Such as `8 Core, 64G`.

**Comment by hippokylejan** [comment]
i use nodeos v1.2.2. it seems that mongodb can use lots of memory. i will try to increase the memory, thanks a lot
