### ISSUE TITLE
cannot sync on kylin-testnet

### ISSUE THREAD

**Issue by hippokylejan** [cryptokylin/CryptoKylin-Testnet#9]
the nodeosd process will log "on_incoming_block    ] 3030001 unlinkable_block_exception: Unlinkable block" for several times and do not receive any new block during the synchronize process

eosio/eos:v1.2.1

**Comment by winlin** [comment]
“Unlinkable block” means illegal blocks，so will be ignored.  and this will not block the sync progress.
